### ISSUE TITLE
Histogram Plots 

### ISSUE THREAD

**Issue by Qazi-Murad** [jackaraz/MA5lib#12]
### Question

Hi, Jackaraz. Sorry for taking your time. I am interested in plotting some histograms related to my work from histo.saf file. I found this tool ma5-expert. I installed it and for histogram plotting or showing, I followed your instructions. It gives an error when running the command plt. hist(.....). The error is "name 'plt' is not defined". I would appreciate any guidance you can give me.

**Comment by jackaraz** [comment]
Hi @Qazi-Murad, have you tried to import the following?

```python
import matplotlib.pyplot as plt
```

**Comment by Qazi-Murad** [comment]
Hi @jackaraz, Now It's working perfectly well. Thank you so much for the quick response. 
One more thing I need to ask. Maybe this is not the right platform. I am working in MA5 expert mode and the goal is to construct mass for a new particle predicted in our model. The process is D-> tb-> Wbb->jjbb. Where D is a new particle, j represents the jet. I do know I need to write a code in MA5 expert mode. I also know the theoretical approach to construction but don't know where to start. Any ideas or experience or advice you like to share?

**Comment by jackaraz** [comment]
Hi @Qazi-Murad, the best place to start is using normal mode and looking into the code. Normal mode does the same thing as the expert mode, but it just writes and executes the code for you so you can generate it and look at the analysis code it writes. The second, more advanced option is to look into the recast codes developed by the users for [PAD](http://madanalysis.irmp.ucl.ac.be/wiki/PublicAnalysisDatabase).

**Comment by Qazi-Murad** [comment]
Hi @jackaraz, this is what exactly I am doing. I tried to produce some histograms for the invariant mass of the top or W boson, and now looking into the code generated by MA5. Thanks
