### ISSUE TITLE
Normalized Distribution to Probabality

### ISSUE THREAD

**Issue by Qazi-Murad** [jackaraz/MA5lib#14]
### Question

Greetings. I am interested in creating a histogram that is normalized to probability, ensuring that the area under the distribution equals 1 with the help of the Ma5_expert tool. I would greatly appreciate any suggestions you may have on this matter.

**Comment by jackaraz** [comment]
Hi @Qazi-Murad, once you extract the histogram ([example here](https://github.com/MadAnalysis/ma5_expert?tab=readme-ov-file#histogram-collection)) you can normalise it as you like, you have all the information you need. You can simply divide the bin outputs by the integral of the histogram.

**Comment by Qazi-Murad** [comment]
Thank you for the suggestion. However, before proceeding, I would like to inquire about the relationship between the SAF file and the C++ script. MadAnalysis5 provides output in three distinct formats. I am seeking clarification on how the value for bin 1 in a C++ or Python file differs from the value for bin 1 in an SAF file. Specifically, I am interested in understanding how to convert the bin value from the SAF file to C++.

**Comment by jackaraz** [comment]
I'm not sure what you are looking for, but the SAF file only includes the total event weight per bin.

**Comment by Qazi-Murad** [comment]
I solved it. Thanks
