### ISSUE TITLE
Can't generate pdf output

### ISSUE THREAD

**Issue by sandeepts224** [jackaraz/MA5lib#2]
When I generate an event madanalysis shows an error. ERROR: MadAnalysis5 failed to create PDF output.
How to solve this? Solutions in Launchpad was not helpful.

**Comment by jackaraz** [comment]
Hi, @sandeepts224 you are asking [madanalysis](https://github.com/MadAnalysis/madanalysis5) related question in ma5_expert module's issues section. These are not the same tools... You need to install latex and pdflatex compilers for PDF to be generated otherwise it will only write an HTML report.

**Comment by Qazi-Murad** [comment]
Hi, Jackaraz. Sorry for taking your time. I am interested in plotting some histograms related to my work from histo.saf file. I found this tool ma5-expert. I installed it and for histogram plotting or showing, I followed your instructions. It gives an error when running the command plt.hist(.....). The error is "name 'plt' is not defined". I would appreciate any guidance you can give me.
