### ISSUE TITLE
jet misidentified as τ _{h}

### ISSUE THREAD

**Issue by GHOUAID** [jackaraz/MA5lib#5]
Dear MA5 team,
i try to generate this SM process p p > w + jet , where one Tau hadronic τ_{h} comes from W decay and the other τ_{h} from a jet misidentified as τ_{h}, my question is, How i can code that   τ_{h} misidentified from jet with expert mode?

**Comment by jackaraz** [comment]
Hi @GHOUAID Ma5-SFS interface has been explained in [this paper](https://arxiv.org/abs/2006.09387).

**Comment by GHOUAID** [comment]
thank you @jackaraz
